StylesPath = .github/styles
MinAlertLevel = suggestion

Vocab = Midnight

# Ignore code and JSX blocks
IgnoredScopes = code, tt

# Ignore inline code
IgnoredPaths = **/_*

Vale.Spelling = NO

# Markdown and MDX
[*.{md,mdx}]
BasedOnStyles = Vale, Midnight
TokenIgnores = (?s)<!--truncate-->, (?s)\{/\*.*?\*/\}