name: Contribute a Blog
description: Suggest or submit a blog post for the Midnight community site.
labels:
  - blog-contrib
body:
  - type: textarea
    id: blog-title
    attributes:
      label: Blog post title
      description: Provide the proposed title for your blog post.
      placeholder: Example Building Midnight
    validations:
      required: true
  - type: textarea
    id: blog-summary
    attributes:
      label: Blog summary
      description: Provide a short summary or abstract of your blog post. What will readers learn?
      placeholder: Summarize the main idea and value of your post in a couple of sentences.
    validations:
      required: true
  - type: checkboxes
    id: blog-topic
    attributes:
      label: Topic area
      description: Select the main topic(s) your blog covers.
      options:
        - label: Building with Compact
          required: false
        - label: Zero-knowledge proofs and privacy
          required: false
        - label: DApp development on Midnight
          required: false
        - label: Tutorials and how-tos
          required: false
        - label: Research or theoretical insights
          required: false
        - label: Community experience or story
          required: false
        - label: Other
          required: false
  - type: textarea
    id: blog-link-or-draft
    attributes:
      label: Draft or example link
      description: If you already have a draft, outline, or sample link, include it here.
  - type: textarea
    id: additional-notes
    attributes:
      label: Additional notes
      description: Add any extra information or context you'd like us to know (optional).