blank_issues_enabled: false
contact_links:
  - name: Midnight Community
    url: https://midnightnetwork.discourse.group/
    about: Join the Midnight Discord to ask questions, share feedback, or connect with other developers building on Midnight.