name: Fix Content
description: Report issues with the Midnight documentation content.
labels: ['fix-content']
body:
  - type: textarea
    id: issue-location
    attributes:
      label: Where is the issue?
      description: Link to the Midnight documentation page(s) where you identified the issue.
      placeholder: The issue is on https://docs.midnight.network/<page>.
  - type: checkboxes
    id: issue-type
    attributes:
      label: Type of issue
      description: Select the type(s) of issue you are reporting.
      options:
        - label: Missing content
          required: false
        - label: Outdated content
          required: false
        - label: Inaccurate content
          required: false
  - type: textarea
    id: issue-description
    attributes:
      label: Description of the issue
      description: Provide a detailed description of the problem, including any relevant context or examples.
  - type: textarea
    id: suggested-change
    attributes:
      label: Suggested change
      description: Suggest a fix or improvement, if you have one.
      placeholder: Leave this section blank if you don't have a suggested change.