name: Site
description: Request updates to the Midnight documentation site that affect its interface, functionality, or infrastructure.
labels:
  - site
body:
  - type: checkboxes
    id: issue-type
    attributes:
      label: Type of site issue
      description: Select the type(s) of site issue you are reporting.
      options:
        - label: Configuration or plugins
          required: false
        - label: UI/UX
          required: false
        - label: Site infrastructure (hosting, deployment)
          required: false
        - label: Other
          required: false
  - type: textarea
    id: issue-description
    attributes:
      label: Issue description
      description: Provide a detailed description of the problem, including any relevant context or examples.
    validations:
      required: true
  - type: textarea
    id: suggested-change
    attributes:
      label: Suggested change
      description: Provide a suggested solution or improvement if available.
      placeholder: Leave this section blank if you do not have a specific suggestion.