extends: substitution
message: "Use '%s' instead of '%s'."
level: warning
ignorecase: true

swap:
  zk proof: zero-knowledge proof
  zk proofs: zero-knowledge proofs
  zkapp: zkApp
  smart-contract: smart contract
  dapp: DApp
  dApp: DApp
  