name: Docs Link Checker

on:
  pull_request:
    paths:
      - "docs/**"
      - "**.md"
      - "**.mdx"

permissions:
  contents: read
  pull-requests: write

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd 

      - name: Get changed files
        id: changed
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 
        with:
          files: |
            **/*.md
            **/*.mdx

      - name: Run Lychee
        uses: lycheeverse/lychee-action@885c65f3dc543b57c898c8099f4e08c8afd178a2 
        id: lychee
        with:
          fail: false
          args: >
            --verbose
            --include-fragments
            ${{ steps.changed.outputs.all_changed_files }}
          output: lychee/report.md

      - name: Comment broken links
        uses: marocchino/sticky-pull-request-comment@70d2764d1a7d5d9560b100cbea0077fc8f633987 
        with:
          path: lychee/report.md