name: Docs Link Checker

on:
  pull_request:
    paths:
      - "docs/**"
      - "**.md"
      - "**.mdx"

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.1

      - name: Get changed files
        id: changed
        uses: tj-actions/changed-files@28b28f6e4e9e3d997beb9dce86cfd8cf0ce7c7f6 # v47.0.3
        with:
          files: |
            **/*.md
            **/*.mdx

      - name: Run Lychee
        uses: lycheeverse/lychee-action@885c65f3dc543b57c898c8099f4e08c8afd178a2 # v2.6.1
        with:
          args: >
            --verbose
            --include-fragments
            ${{ steps.changed.outputs.all_changed_files }}