name: Checkmarx One Scan

on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ 'main' ]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest-8-core-x64
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  #v4.2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@ed196cdaec9cd1bc5aacac4ca2010dd773b20893  #v2.0.35
        with:
          cx_tenant: shielded
          base_uri: https://eu-2.ast.checkmarx.net/
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET_EU }}
          # The below threshold values should be set near current values initially
          additional_params: --threshold "sast-high=1;sast-medium=1;sca-high=24;sca-medium=21;apis-high=1;apis-medium=1;ioc-high=1;ioc-medium=8"
