name: Vale Docs Lint

on:
  pull_request:
    paths:
      - "docs/**"
      - "**.md"
      - "**.mdx"

      
jobs:
  vale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.1

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # 6.3.0
        with:
          node-version: 22
    
      - run: npm install -g mdx2vast

      - name: Run Vale
        uses: errata-ai/vale-action@38bf078c328061f59879b347ca344a718a736018 # v2.1.0
        with:
          reporter: github-pr-review
          filter_mode: added
          files: "docs, sdks"
          fail_on_error: false